#!/bin/bash
# Quick Deploy Links

echo "🚀 RuralCare Connect - Quick Deploy"
echo "=================================="
echo ""
echo "Your code is ready! Now deploy in this order:"
echo ""
echo "1️⃣  BACKEND (Render)"
echo "   👉 https://render.com"
echo "   • New+ → Web Service"
echo "   • Connect GitHub repo: ruralcare-connect"
echo "   • Build: npm install"
echo "   • Start: npm start"
echo "   • Instance: Free"
echo "   ⏱️  Wait 5 min, copy URL"
echo ""
echo "2️⃣  FRONTEND (Vercel)"
echo "   👉 https://vercel.com"
echo "   • Add New → Import from GitHub"
echo "   • Select: ruralcare-connect"
echo "   • Root: client"
echo "   • Add env: VITE_API_BASE_URL=YOUR_RENDER_URL/api"
echo "   ⏱️  Wait 2 min, copy URL"
echo ""
echo "3️⃣  UPDATE RENDER CORS"
echo "   • Go back to Render dashboard"
echo "   • Edit FRONTEND_URL = YOUR_VERCEL_URL"
echo "   • Save (auto redeploys)"
echo ""
echo "✅ DONE! Your app is live!"
echo ""
echo "Test:"
echo "   Backend: https://your-render-url/api/health"
echo "   Frontend: https://your-vercel-url"
echo ""
