import mongoose from 'mongoose';

const reminderSchema = new mongoose.Schema({
    user_id: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    prescriptionId: { type: mongoose.Schema.Types.ObjectId, ref: 'Prescription' },
    appointmentId: { type: mongoose.Schema.Types.ObjectId, ref: 'Appointment' },
    medicineName: { type: String },
    dosage: { type: String },
    frequency: { type: String },
    title: { type: String, required: true },
    description: { type: String },
    reminder_date: { type: String, required: true },
    reminder_time: { type: String, required: true },
    status: { type: String, enum: ['active', 'dismissed', 'completed'], default: 'active' },
    isAutoGenerated: { type: Boolean, default: false },
    notifiedAt: { type: Date }
}, { timestamps: true });

reminderSchema.index({ user_id: 1, reminder_date: 1, reminder_time: 1 });
reminderSchema.index({ prescriptionId: 1, isAutoGenerated: 1 });

const Reminder = mongoose.models.Reminder || mongoose.model('Reminder', reminderSchema);
export default Reminder;
