import Reminder from '../models/Reminder.js';

const DEFAULT_TIMES = {
  morning: '08:00',
  noon: '13:00',
  evening: '20:00',
  night: '22:00'
};

const normalizeFrequency = (frequency = '') => frequency.toLowerCase().trim();

const getTimesForFrequency = (frequency = '') => {
  const value = normalizeFrequency(frequency);

  if (/^\d-\d-\d$/.test(value)) {
    const [morning, noon, night] = value.split('-').map(Number);
    const times = [];
    if (morning > 0) times.push(DEFAULT_TIMES.morning);
    if (noon > 0) times.push(DEFAULT_TIMES.noon);
    if (night > 0) times.push(DEFAULT_TIMES.evening);
    return times.length ? times : [DEFAULT_TIMES.morning];
  }

  if (/(three|thrice|tid|3 times|3x)/.test(value)) {
    return [DEFAULT_TIMES.morning, '14:00', DEFAULT_TIMES.evening];
  }

  if (/(twice|bid|2 times|2x)/.test(value)) {
    return ['09:00', '21:00'];
  }

  if (/(night|bedtime)/.test(value)) {
    return [DEFAULT_TIMES.night];
  }

  return ['09:00'];
};

const parseDurationDays = (duration = '') => {
  const matched = `${duration}`.match(/(\d+)/);
  const days = matched ? Number(matched[1]) : 7;
  if (!Number.isFinite(days) || days < 1) return 7;
  return Math.min(days, 30);
};

const formatDate = (date) => {
  const year = date.getFullYear();
  const month = `${date.getMonth() + 1}`.padStart(2, '0');
  const day = `${date.getDate()}`.padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const createAutoRemindersForPrescription = async ({ patientId, prescriptionId, appointmentId, medicines = [], session = null }) => {
  const queryOpts = session ? { session } : undefined;

  await Reminder.deleteMany({ user_id: patientId, prescriptionId, isAutoGenerated: true }, queryOpts);

  const reminders = [];
  const startDate = new Date();

  medicines.forEach((medicine) => {
    const times = getTimesForFrequency(medicine.frequency);
    const days = parseDurationDays(medicine.duration);

    for (let dayOffset = 0; dayOffset < days; dayOffset += 1) {
      const reminderDate = new Date(startDate);
      reminderDate.setDate(startDate.getDate() + dayOffset);
      const reminder_date = formatDate(reminderDate);

      times.forEach((reminder_time) => {
        reminders.push({
          user_id: patientId,
          prescriptionId,
          appointmentId,
          medicineName: medicine.name,
          dosage: medicine.dosage,
          frequency: medicine.frequency,
          title: medicine.name,
          description: `${medicine.dosage} | ${medicine.frequency} | ${medicine.duration}`,
          reminder_date,
          reminder_time,
          status: 'active',
          isAutoGenerated: true
        });
      });
    }
  });

  if (reminders.length > 0) {
    await Reminder.insertMany(reminders, { ordered: false, ...(session ? { session } : {}) });
  }

  return reminders.length;
};
